version: "1"

services:
  - type: web
    name: skill-island-api
    env: docker
    rootDir: services/api
    dockerfilePath: ./Dockerfile.prod
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: "postgres://user:password@endpoint.neon.tech/neondb?sslmode=require"
      - key: ALLOWED_ORIGINS
        value: "https://skill-island.vercel.app,http://localhost:3000"
